# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# curseforge information
projectId = 656147
curse_type = beta
modrinthId = EFoYZIZL

mixingradle_version = 0.7-SNAPSHOT
cursegradle_version = 1.4.0
# github information 
github_project = TeamMoegMC/Caupona

# dependency version
jei_version = 29.5.0.26
patchouli_version = 87-NEOFORGE-SNAPSHOT

#subsystems
#neogradle.subsystems.parchment.minecraftVersion=1.21.11
#neogradle.subsystems.parchment.mappingsVersion=2025.12.20
minecraft_version=26.1.2
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[26.1.2]
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=26.1.2.36-beta
# mod version info
mc_version=26
version_neogradle=7.1.21
top_version=1.21_neo-12.0.3-5

#mod info
mod_id=caupona
# The human-readable display name for the mod.
mod_name=Caupona
# The mod version. See https://semver.org/
mod_version=6.0
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.khjxiaogu

